### ISSUE TITLE
Error whilst accessing profiles (sometimes)

### ISSUE THREAD

**Issue by sakunc** [Pixure/issues#1]
Profile pages work, however under strange circumstances, the profile page returns an error message unless you use private browsing.

Still haven't pinpointed the cause

**Comment by sakofchit** [comment]
Looks fine for now, gonna leave this one open though since it's still unpredictable

**Comment by sakofchit** [comment]
Nevermind, it happens when you change layouts. 🤔

**Comment by sakofchit** [comment]
Issue persists in private/incognito mode

**Comment by sakofchit** [comment]
Fixed a while ago
