### ISSUE TITLE
Profile Picture Update is Broken

### ISSUE THREAD

**Issue by EthanMcFarlin** [Pixure/issues#11]
Profile Picture upload is instantaneous. Updating a pre-existing profile picture does not function (or in the very least lags behind and updates 20+ minutes after).

**Comment by sakofchit** [comment]
Pretty sure this is a caching thing. I'll take a look

**Comment by sakofchit** [comment]
Seems like it was. I set the cache thing to ~15 minutes to reduce the website's load speeds. I've reduced it to 3 minutes, so it should (ideally) be fine
