### ISSUE TITLE
Audio File Playback Dysfunctional

### ISSUE THREAD

**Issue by EthanMcFarlin** [Pixure/issues#14]
Upload worked correctly, as did the video for approximately 10 minutes. Now, whenever being clicked on, an error message appears.

![image](https://user-images.githubusercontent.com/34318060/36940599-450d248c-1f03-11e8-8009-5e4c155a48b0.png)

**Comment by sakofchit** [comment]
![image](https://user-images.githubusercontent.com/7917503/37566800-64c0db6a-2a94-11e8-9830-b5b1a1d6a6b5.png)
Fixed
