### ISSUE TITLE
Liking comments

### ISSUE THREAD

**Issue by Darfisse** [Pixure/issues#16]
When liking a comment, the pink heart only appears momentarily when clicked before disappearing.

**Comment by sakofchit** [comment]
_Side note: The issue persisted in liking content as well in addition to liking comments._

I spent almost an hour trying to figure this out till I found out that there's this thing called "switchClass" in JavaScript, which can switch between different classes upon the click of a button. With the liking system, we have 2 classes: one for non-liked/unliking and one for liking.

.toggleClass (which is the one we had initially) did what you described
.addClass (which is what I tried out) added color upon clicking the like button, but kept it there regardless of whether or not you liked or unliked it.
.switchClass though 👌

im a fucking retard 🤦‍♂️ smh
