### ISSUE TITLE
Broken Image Proportions on Logo

### ISSUE THREAD

**Issue by EthanMcFarlin** [Pixure/issues#9]
Logo nested in navigation bar appears to be stretched horizontally:
![image](https://user-images.githubusercontent.com/34318060/36940234-536cd600-1efc-11e8-8ebd-b28c2baaeffa.png)

Also, as a minor aesthetic feature, you may consider minimizing the logo by removing its text upon scrolling down to reduce the navigation height.

**Comment by sakofchit** [comment]
Fixed
